version: '3.7'

services:
  dev-keycloak:
    image: jboss/keycloak:8.0.2
    container_name: dev-keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
    networks:
      - pipeline_pipeline-net
networks:
  pipeline_pipeline-net:
    external: true
