version: "3.7"

services:
  dev-keycloak:
    image: jboss/keycloak
    container_name: dev-keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
