version: "3.7"

services:
  webgen-keycloak:
    image: jboss/keycloak
    container_name: webgen-auth
    restart: unless-stopped
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
